import assert from "node:assert/strict";import test from "node:test";
import {HtmlReportRenderer,buildReportViewModel,escapeReportHtml,type ReportDefinition} from "../src/shared/report";
type Data={title:string};
const definition:ReportDefinition<Data>={key:"approval-report",version:"1",templateKey:"approval-html",templateVersion:"1",outputTypes:["html"],validateData(value){if(!value||typeof value!=="object"||typeof (value as {title?:unknown}).title!=="string")throw new TypeError("invalid report data");return{title:(value as {title:string}).title};}};
const build=(data:unknown={title:"Tokyo <Trip>"})=>buildReportViewModel({definition,resourceRef:{type:"request",id:"req-1"},sourceSnapshot:{id:"snap-1",sourceVersion:"7",capturedAt:"2026-10-05T00:00:00.000Z",masterRevisionRefs:["office-r3"]},generationIntent:"original",generatedBy:"user-1",generatedAt:"2026-10-05T00:01:00.000Z",locale:"ja-JP",timezone:"Asia/Tokyo",data});
test("report builder validates data and fixes historical/version metadata",()=>{const vm=build();assert.equal(vm.definitionVersion,"1");assert.equal(vm.templateVersion,"1");assert.equal(vm.sourceSnapshot.id,"snap-1");assert.equal(vm.sourceSnapshot.masterRevisionRefs?.[0],"office-r3");assert.throws(()=>build({title:1}),/invalid report data/);});
test("HTML renderer receives report view model and escaped business text",async()=>{const renderer=new HtmlReportRenderer(()=>({key:"approval-html",version:"1",render:(vm)=>`<!doctype html><html><body><h1>${escapeReportHtml((vm.data as Data).title)}</h1></body></html>`}));const rendered=await renderer.render({definition,viewModel:build(),outputType:"html"});assert.match(new TextDecoder().decode(rendered.body),/Tokyo &lt;Trip&gt;/);});
test("HTML renderer rejects active and external content",async()=>{const renderer=new HtmlReportRenderer(()=>({key:"approval-html",version:"1",render:()=>'<html><body><img src="https://example.com/x.png"></body></html>'}));await assert.rejects(renderer.render({definition,viewModel:build(),outputType:"html"}),/forbidden/);});
test("report builder rejects invalid locale and timezone instead of using runtime defaults",()=>{
  assert.throws(()=>buildReportViewModel({definition,resourceRef:{type:"request",id:"req-1"},sourceSnapshot:{id:"snap-1",sourceVersion:"7",capturedAt:"2026-10-05T00:00:00.000Z"},generationIntent:"original",generatedBy:"user-1",generatedAt:"2026-10-05T00:01:00.000Z",locale:"not_a_locale",timezone:"Asia/Tokyo",data:{title:"x"}}),/BCP 47/);
  assert.throws(()=>buildReportViewModel({definition,resourceRef:{type:"request",id:"req-1"},sourceSnapshot:{id:"snap-1",sourceVersion:"7",capturedAt:"2026-10-05T00:00:00.000Z"},generationIntent:"original",generatedBy:"user-1",generatedAt:"2026-10-05T00:01:00.000Z",locale:"ja-JP",timezone:"Local/System",data:{title:"x"}}),/IANA/);
});
