import { buildReportViewModel, escapeReportHtml, type PdfTextTemplate, type ReportDefinition, type ReportViewModel, type SafeHtmlTemplate } from "../../shared/report";
import type { TravelRequestRecord } from "./travel-request";
import type { WorkflowInstanceRecord } from "../../worker/workflow";
import type { ResolvedMasterValue } from "../../worker/master-data";
import type { BusinessActivityRecord } from "../../worker/business-activity";

export const WORKHUB_TRAVEL_APPROVAL_REPORT_KEY="workhub.travel-approval";
export interface WorkhubTravelApprovalReportData {requestId:string;requesterId:string;destinationOfficeLabel:string;startDate:string;endDate:string;purpose:string;approvedBy:string;approvedAt:string;}
const validateWorkhubTravelApprovalData=(value:unknown):WorkhubTravelApprovalReportData=>{if(!value||typeof value!=="object")throw new TypeError("travel approval report data is invalid");const v=value as Record<string,unknown>;for(const key of ["requestId","requesterId","destinationOfficeLabel","startDate","endDate","purpose","approvedBy","approvedAt"])if(typeof v[key]!=="string"||!(v[key] as string).trim())throw new TypeError(`${key} is invalid`);return v as unknown as WorkhubTravelApprovalReportData;};
export const WORKHUB_TRAVEL_APPROVAL_REPORT:ReportDefinition<WorkhubTravelApprovalReportData>={
 key:WORKHUB_TRAVEL_APPROVAL_REPORT_KEY,version:"1",templateKey:"workhub.travel-approval.html",templateVersion:"1",outputTypes:["html"],
 validateData:validateWorkhubTravelApprovalData
};
export const WORKHUB_TRAVEL_APPROVAL_PDF_REPORT:ReportDefinition<WorkhubTravelApprovalReportData>={key:WORKHUB_TRAVEL_APPROVAL_REPORT_KEY,version:"1",templateKey:"workhub.travel-approval.pdf",templateVersion:"1",outputTypes:["pdf"],validateData:validateWorkhubTravelApprovalData};
const buildWorkhubTravelApprovalReportFor=(definition:ReportDefinition<WorkhubTravelApprovalReportData>,input:{travel:TravelRequestRecord;workflow:WorkflowInstanceRecord;office:ResolvedMasterValue;approval:BusinessActivityRecord;generatedBy:string;generatedAt:string;}):ReportViewModel<WorkhubTravelApprovalReportData>=>{
 if(input.travel.status!=="submitted"||input.workflow.state!=="completed"||!input.workflow.completedAt)throw new TypeError("travel approval report requires a completed workflow");
 if(input.travel.workflowInstanceId!==input.workflow.id||input.workflow.resourceId!==input.travel.id)throw new TypeError("workflow does not belong to travel request");
 if(!input.travel.destinationOfficeRevisionId||input.office.revision.id!==input.travel.destinationOfficeRevisionId)throw new TypeError("historical office revision does not match travel request");
 if(input.approval.activityType!=="workflow.approved"||input.approval.resourceId!==input.travel.id||!input.approval.actorRef)throw new TypeError("approval activity does not match travel request");
 return buildReportViewModel({definition,resourceRef:{type:input.workflow.resourceType,id:input.travel.id},sourceSnapshot:{id:`travel-${input.travel.id}-workflow-${input.workflow.version}`,sourceVersion:`${input.travel.version}:${input.workflow.version}`,capturedAt:input.workflow.completedAt,masterRevisionRefs:[input.office.revision.id],decisionRefs:[input.approval.sourceId]},generationIntent:"original",generatedBy:input.generatedBy,generatedAt:input.generatedAt,locale:"ja-JP",timezone:"Asia/Tokyo",data:{requestId:input.travel.id,requesterId:input.travel.requesterId,destinationOfficeLabel:input.office.revision.label,startDate:input.travel.startDate,endDate:input.travel.endDate,purpose:input.travel.purpose,approvedBy:input.approval.actorRef,approvedAt:input.approval.occurredAt}});
};
export const buildWorkhubTravelApprovalReport=(input:Parameters<typeof buildWorkhubTravelApprovalReportFor>[1])=>buildWorkhubTravelApprovalReportFor(WORKHUB_TRAVEL_APPROVAL_REPORT,input);
export const buildWorkhubTravelApprovalPdfReport=(input:Parameters<typeof buildWorkhubTravelApprovalReportFor>[1])=>buildWorkhubTravelApprovalReportFor(WORKHUB_TRAVEL_APPROVAL_PDF_REPORT,input);
export const WORKHUB_TRAVEL_APPROVAL_HTML_TEMPLATE:SafeHtmlTemplate<WorkhubTravelApprovalReportData>={key:"workhub.travel-approval.html",version:"1",render(vm){const d=vm.data;return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>Travel approval</title></head><body><h1>出張申請 承認結果</h1><dl><dt>申請ID</dt><dd>${escapeReportHtml(d.requestId)}</dd><dt>申請者</dt><dd>${escapeReportHtml(d.requesterId)}</dd><dt>出張先</dt><dd>${escapeReportHtml(d.destinationOfficeLabel)}</dd><dt>期間</dt><dd>${escapeReportHtml(d.startDate)} - ${escapeReportHtml(d.endDate)}</dd><dt>目的</dt><dd>${escapeReportHtml(d.purpose)}</dd><dt>承認者</dt><dd>${escapeReportHtml(d.approvedBy)}</dd><dt>承認日時</dt><dd>${escapeReportHtml(d.approvedAt)}</dd></dl></body></html>`;}};
export const WORKHUB_TRAVEL_APPROVAL_PDF_TEMPLATE:PdfTextTemplate<WorkhubTravelApprovalReportData>={key:"workhub.travel-approval.pdf",version:"1",build(vm){const d=vm.data;return{title:"Travel Approval",lines:["Travel Approval",`Request ID: ${d.requestId}`,`Requester: ${d.requesterId}`,`Destination: ${d.destinationOfficeLabel}`,`Period: ${d.startDate} - ${d.endDate}`,`Purpose: ${d.purpose}`,`Approved by: ${d.approvedBy}`,`Approved at: ${d.approvedAt}`]};}};
